# Add the actual name of your custom nlp provider.
# Specify the sugestion endpoint per environemnt.
custom_nlp_provider_name:
  suggestion_endpoint:
      development: http://custom-nlp-provider.dev/suggest
      test: http://custom-nlp-provider.test/suggest
      staging: http://custom-nlp-provider-staging.org/suggest
      production: http://custom-nlp-provider.org/suggest
  multiple_suggestion_endpoint:
      development: http://custom-nlp-provider.dev/multiple_suggest
      test: http://custom-nlp-provider.test/multiple_suggest
      staging: http://custom-nlp-provider-staging.org/multiple_suggest
      production: http://custom-nlp-provider.org/multiple_suggest
  suggestion_endpoint_credentials:
      development:
          "username": testuser
          "password": password
      test:
          "username": testuser
          "password": password
